### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by ereneum** [typicalname500/Discord-bot-that-utilizes-fifteen.ai#8]
_Hello sir,
  After not finding any link for communication, I decided to post here, but I probably made a mistake due to a funny mistake and lack of information so I didn't want to write it here. The problem is that even though I have done all the steps regarding TokenConfig I get an error like this that I don't understand why. I am a Java developer and know only the basics about python but I really want to add this bot to my server. 
Thank you._

C:\Users\alier\AppData\Local\Programs\Python\Python39\python.exe C:/Users/alier/Desktop/Discord-bot-that-utilizes-fifteen.ai-Python/Discord-Bot1.py
Traceback (most recent call last):
  File "C:\Users\alier\Desktop\Discord-bot-that-utilizes-fifteen.ai-Python\Discord-Bot1.py", line 26, in <module>
    data = json.load(json_file)
  File "C:\Users\alier\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\alier\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\alier\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\alier\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 1 column 114 (char 113)

Process finished with exit code 1

**Comment by typicalname500** [comment]
Hi Ali,

Thanks for getting in touch, I'll make sure to add a link to contact me in the README.md file.

I think I've managed to replicate the issue. It seemed that any delay in loading/ using the "json_file" variable in something like a print can output a similar error.

Can you try using the following instead of what is on lines 16-28? 

``` python

#Opening JSON files and storing information as object variables
with open('characters.json') as json_file:
    string0 = json_file.read()

data0 = json.loads(string0)    
Character_info = data0
data0 = None

with open('CustomAPIConfig.json') as json_file:
    string1 = json_file.read()

data1 = json.loads(string1)
CustomAPI_info = data1
data1 = None

with open('TokenConfig.json') as json_file:
    string2 = json_file.read()

data2 = json.loads(string2)
Token_info = data2
data2 = None 
```

If this still throws an error, can you check to see if there is a `'\'` within your token? If there is, can you try "escaping" it by adding another  `'\'` before/after the character and see if that works instead?

**Comment by ereneum** [comment]
It gave an error but I solved it. 

In the text you wrote for the tokenconfig file, needs one more \ to behind characters.json and the first letter of the Token must be lowercase.

final version :

{
  "token": "mytoken",
  "Prefix": ";",
  "CharacterInfoFile": "C:\\\ProgramLocation\\\characters.json",
  "SingleAudiofilepath": "C:\\\Test Directory\\\\"
}

Thank you sir, I am happy to add this bot to my server. ^^
